### ISSUE TITLE
not signed on ios

### ISSUE THREAD

**Issue by gedw99** [dan-v/dosxvpn#12] opened 2017-12-11 21:06 UTC
![ss](https://user-images.githubusercontent.com/20677314/33853730-47674b88-debf-11e7-8800-9e62ce5c9677.png)

anyone know why ?

all i did is install the Apple Config: /Users/apple/.dosxvpn/dosxvpn-232-ams2.apple.mobileconfig

do i need to add extra info  from the outputs when installing on ios ?
Apple Config: /Users/apple/.dosxvpn/dosxvpn-232-ams2.apple.mobileconfig
2017/12/11 18:58:21 Android Config: /Users/apple/.dosxvpn/dosxvpn-232-ams2.android.sswan
2017/12/11 18:58:21 Client Private Key: /Users/apple/.dosxvpn/dosxvpn-232-ams2.client.cert.p12
2017/12/11 18:58:21 Client Private Key Passphrase: XXXXXXXXXXXX
2017/12/11 18:58:21 CA Certificate: /Users/apple/.dosxvpn/dosxvpn-232-ams2.ca.cert.pem
2017/12/11 18:58:21 Server Certificate: /Users/apple/.dosxvpn/dosxvpn-232-ams2.server.cert.pem

thanks in advance... this VPN stuff is a bit cryptic... sorry

**Comment by dan-v** [comment] 2017-12-11 23:33
@gedw99 - I don't have an iPhone, so I don't have much knowledge on how it handles certificates, but I'm guessing it is just saying it doesn't trust this generated self signed SSL certificate (which is expected). I'm curious if the VPN still functions in this state?

**Comment by gedw99** [comment] 2017-12-12 09:20
@dan-v 

yes it still works perfectly.

I dont have an iphone myself and in the ios Simulator there is no VPN functionality.
SO i asked a few friends to try it. They tested on iphone 5 and iphone 6, and it works perfectly. On iphone 5 there is an issue with using it over wifi, where its slow to the point of being useless. This is 

Regarding the Certificate, i also dont really have a glue what it could be. 
I think put htis one on the back log and come back to it.

**Comment by dan-v** [comment] 2017-12-13 22:53
Going to close this as it's seems to be working as intended. I'm actually surprised it even works on iPhone 5, as it's fairly old in terms of phones and stopped getting updates I think.

**Closed by dan-v** 2017-12-13 22:53 UTC

**Comment by gedw99** [comment] 2017-12-14 13:36
ah there is a bug on iphone 5 :)
Over LTE works fine
Over wifi it crawls.

Nothing we can do about that one...
